num1=int(input("enter first 10- digit number:"))
num2=int(input("enter the second 10-digit numbers"))
print("relational operations")
print("num1",num1)
print("num2,"num2)
print("num3!=num4",num1!=num2)
print("num1==num2",num1==num2)
print("num1>num2",num1>num2)
print("num1<num2",num1<num2)
print("num1<=num2",num1<=num2)
print("num1>=num2",num1>=num2)
